// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5dGBQrWzVVW7x-eNhGVZYzZuka_gW1k',
    appId: '1:451713665228:android:3d95b73e22237e0277da69',
    messagingSenderId: '451713665228',
    projectId: 'healthpanda-8110d',
    databaseURL: 'https://healthpanda-8110d-default-rtdb.firebaseio.com',
    storageBucket: 'healthpanda-8110d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3zhJ0PSULLO4h2Nfa-nInpwNLRgJk-PI',
    appId: '1:451713665228:ios:efae7c8878a487f177da69',
    messagingSenderId: '451713665228',
    projectId: 'healthpanda-8110d',
    databaseURL: 'https://healthpanda-8110d-default-rtdb.firebaseio.com',
    storageBucket: 'healthpanda-8110d.appspot.com',
    iosBundleId: 'com.pandahealth.hospital',
  );

}